version: '3.7'
services:
  account:
    image: ghcr.io/4sitive/account:latest
    restart: always
    container_name: account
    hostname: account
    network_mode: bridge
    environment:
      JAVA_OPTS: >-
        -Dfile.encoding=UTF-8
        -Dcrypto.policy=unlimited
        -Dsun.net.inetaddr.ttl=0
        -Dsun.net.inetaddr.negative.ttl=0
        -Djava.net.preferIPv4Stack=true
        -Djava.security.egd=file:/dev/./urandom
        -Duser.country=KR
        -Duser.language=ko
        -Duser.timezone=Asia/Seoul
      SPRING_PROFILES_ACTIVE: production
      LOG_PATH: /workspace/log
      SERVER_PORT: 18080
      MANAGEMENT_SERVER_PORT: 18081
      AUTHORIZATIONSERVERSECURITY_KEY: $KEY
      AUTHORIZATIONSERVERSECURITY_PRIVATEKEY: $PRIVATEKEY
      AUTHORIZATIONSERVERSECURITY_PUBLICKEY: $PUBLICKEY
      SPRING_DATASOURCE_PASSWORD: $DATASOURCE_PASSWORD
      SPRING_REDIS_PASSWORD: $REDIS_PASSWORD
      SPRING_DATA_MONGODB_URI: $MONGODB_URI
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET: $OAUTH2_GOOGLE_CLIENTSECRET
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENTSECRET: $OAUTH2_KAKAO_CLIENTSECRET
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENTSECRET: $OAUTH2_NAVER_CLIENTSECRET
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENTSECRET: $OAUTH2_FACEBOOK_CLIENTSECRET
    ports:
      - "18080:18080"
      - "18081:18081"