spring:
  application:
    name: account
  profiles:
    group:
      default: LOGGING_CONSOLE
  security:
    oauth2:
      client:
        provider:
          'GOOGLE':
            user-info-authentication-method: header
            authorization-uri: https://accounts.google.com/o/oauth2/auth?approval_prompt=force&access_type=offline
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: id
          'KAKAO':
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: post
            user-name-attribute: id
        registration:
          'GOOGLE':
            client-name: 'Google 로그인'
            client-id: 572557505346-38m9fuqjn2momnvp63fs7tu9mmv3nbv3.apps.googleusercontent.com
            client-secret: BHZeyK0Au4XsflIn6Iqy9g7w
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
          'KAKAO':
            client-name: '카카오 로그인'
            client-id: 345b0cf914e6e65cff98a07215b6a244
            client-secret: 1gqtgi2kT0tahZn914nC5rG5f3SDmb5r
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - profile
#              - account_email
  config:
    import: optional:classpath:security.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.globally_quoted_identifiers: true
  datasource:
    platform: h2
server:
  forward-headers-strategy: framework
#openssl rsa -in private.pem -pubout -out public.pem
