spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?createDatabaseIfNotExist=true&allowMultiQueries=true&useUnicode=true&connectTimeout=2000&socketTimeout=10000&autoReconnect=true&autoReconnectForPools=true&useSSL=false&serverZoneId=Asia/Seoul&characterEncoding=utf8