spring:
  application:
    name: account
  profiles:
    group:
      default: LOGGING_CONSOLE
  security:
    oauth2:
      client:
        provider:
          'google':
            user-info-authentication-method: header
            authorization-uri: https://accounts.google.com/o/oauth2/auth?approval_prompt=force&access_type=offline
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: id
          'kakao':
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: post
            user-name-attribute: id
          'naver':
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: post
            user-name-attribute: id
          'facebook':
            authorization-uri: https://www.facebook.com/v2.8/dialog/oauth
            token-uri: https://graph.facebook.com/v2.8/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-info-authentication-method: post
            user-name-attribute: id
        registration:
          'google':
            client-name: 'Google 로그인'
            client-id: 572557505346-7gi9f2e2mb7vo1sldp6ru96nlitc9ram.apps.googleusercontent.com
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
          'kakao':
            client-name: '카카오 로그인'
            client-id: 53dc9f6849554ef4b1f2387c3baddf4c
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - profile
              - account_email
          'naver':
            client-name: '네이버 로그인'
            client-id: XGZpumnYsTg1ZH1fEHno
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - profile
          'facebook':
            client-name: 'Facebook 로그인'
            client-id: 182033933860557
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post
            scope:
              - public_profile
              - email
  config:
    import: optional:classpath:security.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.globally_quoted_identifiers: true
  datasource:
    continue-on-error: true
    initialization-mode: always
    platform: h2
    url: jdbc:mysql://4sitive.mysql.database.azure.com:3306/daymotion?useSSL=true&requireSSL=false
    username: sitive4@4sitive
    hikari:
      auto-commit: false
      max-lifetime: 3600
  redis:
    host: 4sitive.redis.cache.windows.net
    lettuce:
      pool:
        max-wait: 1S
        min-idle: 1
server:
  forward-headers-strategy: framework
#openssl rsa -in private.pem -pubout -out public.pem
