spring:
  datasource:
    url: jdbc:mysql://4sitive.mysql.database.azure.com:3306/daymotion?useSSL=true&requireSSL=false
    username: sitive4@4sitive
  redis:
    host: 4sitive.redis.cache.windows.net