name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw -B spring-boot:build-image --file pom.xml -Dspring-boot.build-image.imageName=ghcr.io/4sitive/account
  deploy:
    needs: build
    runs-on: [ self-hosted ]
    steps:
      - name: Deploy with Docker
        env:
          KEY: ${{secrets.KEY}}
          PRIVATEKEY: ${{secrets.PRIVATE_KEY}}
          PUBLICKEY: ${{secrets.PUBLIC_KEY}}
          DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          OAUTH2_GOOGLE_CLIENTSECRET: ${{secrets.OAUTH2_GOOGLE_CLIENTSECRET}}
          OAUTH2_KAKAO_CLIENTSECRET: ${{secrets.OAUTH2_KAKAO_CLIENTSECRET}}
          OAUTH2_NAVER_CLIENTSECRET: ${{secrets.OAUTH2_NAVER_CLIENTSECRET}}
          OAUTH2_FACEBOOK_CLIENTSECRET: ${{secrets.OAUTH2_FACEBOOK_CLIENTSECRET}}
        run: |
          docker-compose up --no-deps --build --force-recreate --detach
